# 100 numpy exercises



#### 1. Import the numpy package under the name `np` (★☆☆)

In [189]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [190]:
np.__version__

'2.2.6'

#### 3. Create a null vector of size 10 (★☆☆)

In [191]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [192]:
print("%d bytes" %(arr.size * arr.itemsize))

80 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [193]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [194]:
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [195]:
arr =np.arange(10,50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [196]:
arr[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [197]:
arr=np.random.randint(0,9,size=(3,3))
arr

array([[6, 7, 5],
       [6, 3, 5],
       [5, 2, 4]], dtype=int32)

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [198]:
arr = np.array( [1,2,0,0,4,0]).nonzero()
arr

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [199]:
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [200]:
arr = np.random.random(size=(3,3,3))
arr

array([[[0.12481225, 0.08943153, 0.8511528 ],
        [0.92946375, 0.21592897, 0.4514498 ],
        [0.10439929, 0.08312003, 0.97562225]],

       [[0.6540985 , 0.40300525, 0.42396769],
        [0.67551225, 0.95080167, 0.77562638],
        [0.47146973, 0.94484364, 0.2804289 ]],

       [[0.53417332, 0.46225994, 0.55745746],
        [0.5859838 , 0.28526809, 0.31199888],
        [0.1349776 , 0.9288334 , 0.5583284 ]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [201]:
arr =np.random.random(size=(10,10))
print(arr.min())
print(arr.max())

0.000908688154055759
0.9951667729364978


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [202]:
arr = np.random.random((30))
print(arr)
print(arr.mean())

[0.16075289 0.72867552 0.60249774 0.04515042 0.75188209 0.63919135
 0.15692908 0.81359987 0.69896634 0.04829394 0.43460597 0.85271996
 0.08821808 0.2932651  0.68256376 0.267162   0.66508085 0.99910446
 0.98774862 0.54346787 0.08261011 0.39041284 0.81099112 0.21786581
 0.54131912 0.06171081 0.56633466 0.87414983 0.92878492 0.44508393]
0.512637968638612


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [203]:
arr=np.zeros((10,10))
arr[:,0]=1
arr[:,-1]=1
arr[0,:]=1
arr[-1,:]=1

arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [204]:
np.info(np.pad)

Pad an array.

Parameters
----------
array : array_like of rank N
    The array to pad.
pad_width : {sequence, array_like, int}
    Number of values padded to the edges of each axis.
    ``((before_1, after_1), ... (before_N, after_N))`` unique pad widths
    for each axis.
    ``(before, after)`` or ``((before, after),)`` yields same before
    and after pad for each axis.
    ``(pad,)`` or ``int`` is a shortcut for before = after = pad width
    for all axes.
mode : str or function, optional
    One of the following string values or a user supplied function.

    'constant' (default)
        Pads with a constant value.
    'edge'
        Pads with the edge values of array.
    'linear_ramp'
        Pads with the linear ramp between end_value and the
        array edge value.
    'maximum'
        Pads with the maximum value of all or part of the
        vector along each axis.
    'mean'
        Pads with the mean value of all or part of the
        vector along each axis.
    'media

In [205]:
arr=np.random.randint(10,90,size=(8,8))
arr=np.pad(arr,pad_width=1,mode='constant',constant_values=0)
arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 29, 70, 25, 71, 25, 33, 16, 44,  0],
       [ 0, 61, 87, 52, 73, 10, 40, 53, 85,  0],
       [ 0, 11, 39, 16, 72, 22, 71, 22, 35,  0],
       [ 0, 69, 47, 55, 76, 22, 81, 84, 14,  0],
       [ 0, 44, 21, 57, 72, 70, 40, 72, 66,  0],
       [ 0, 23, 84, 66, 20, 11, 56, 43, 81,  0],
       [ 0, 76, 36, 69, 85, 38, 10, 13, 83,  0],
       [ 0, 77, 84, 13, 72, 74, 29, 55, 65,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]], dtype=int32)

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [206]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [207]:
arr=np.diag(np.arange(1,5),k=-1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [208]:
arr=np.zeros((8,8))
arr[1::2,::2]=1
arr[::2,1::2]=1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [209]:
import numpy as np

shape = (6, 7, 8)
linear_index = 99 # for the 100th element

index = np.unravel_index(linear_index, shape)

print(f"The shape is: {shape}")
print(f"The linear index of the 100th element is: {linear_index}")
print(f"The multi-dimensional index (x,y,z) is: {index}")

The shape is: (6, 7, 8)
The linear index of the 100th element is: 99
The multi-dimensional index (x,y,z) is: (np.int64(1), np.int64(5), np.int64(3))


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [210]:
arr=np.random.random((6,7,8))
index = np.unravel_index(100,arr.shape)
index

(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [211]:
arr=np.random.random((8,8))
arr=np.tile(arr,(4,4))
arr

array([[0.71715267, 0.08840646, 0.58193982, 0.82849098, 0.74069533,
        0.51798709, 0.40958594, 0.5928394 , 0.71715267, 0.08840646,
        0.58193982, 0.82849098, 0.74069533, 0.51798709, 0.40958594,
        0.5928394 , 0.71715267, 0.08840646, 0.58193982, 0.82849098,
        0.74069533, 0.51798709, 0.40958594, 0.5928394 , 0.71715267,
        0.08840646, 0.58193982, 0.82849098, 0.74069533, 0.51798709,
        0.40958594, 0.5928394 ],
       [0.56001758, 0.57361897, 0.69736342, 0.39757385, 0.73521877,
        0.37215901, 0.59679216, 0.30294238, 0.56001758, 0.57361897,
        0.69736342, 0.39757385, 0.73521877, 0.37215901, 0.59679216,
        0.30294238, 0.56001758, 0.57361897, 0.69736342, 0.39757385,
        0.73521877, 0.37215901, 0.59679216, 0.30294238, 0.56001758,
        0.57361897, 0.69736342, 0.39757385, 0.73521877, 0.37215901,
        0.59679216, 0.30294238],
       [0.21092466, 0.03372479, 0.43240679, 0.80094025, 0.59951697,
        0.64855807, 0.91077817, 0.80844562, 0.2109

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [212]:
arr=np.random.random((5,5))
arr_norm=(arr-arr.min())/(arr.max()-arr.min())
print(arr)
print('___________'*5)
print(arr_norm)

[[0.50817574 0.60041426 0.32115663 0.25282538 0.00456983]
 [0.43140281 0.89184122 0.57956997 0.48654808 0.40727156]
 [0.63820119 0.55592278 0.36542598 0.66655248 0.49375565]
 [0.66051726 0.16804981 0.33136308 0.79476061 0.33367594]
 [0.18090281 0.10993612 0.44955356 0.01671059 0.92754207]]
_______________________________________________________
[[0.54563495 0.64557135 0.34300793 0.26897402 0.        ]
 [0.46245484 0.96131969 0.62298747 0.52220233 0.43630969]
 [0.68651183 0.59736677 0.39097183 0.71722921 0.53001141]
 [0.71069031 0.1771234  0.35406618 0.8561371  0.35657206]
 [0.19104906 0.11415976 0.48212039 0.01315398 1.        ]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [213]:
np.dtype([('r', np.ubyte, 1),
          ('g', np.ubyte, 1),
          ('b', np.ubyte, 1),
          ('a', np.ubyte, 1)])

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [214]:
M5X3 = np.random.randint(1,10,(5,3))
M3X2 = np.random.randint(1,10,(3,2))
print(M5X3)
print('___________')
print(M3X2)
print('___________')
print(M5X3*M5X3)
print('___________')
np.dot(M5X3,M3X2)
#np.dot(np.random.randint(1,10,(5,3)), np.random.randint(1,10,(3,2)))

[[7 9 7]
 [6 5 3]
 [3 6 9]
 [5 9 6]
 [3 9 3]]
___________
[[3 5]
 [5 3]
 [3 6]]
___________
[[49 81 49]
 [36 25  9]
 [ 9 36 81]
 [25 81 36]
 [ 9 81  9]]
___________


array([[ 87, 104],
       [ 52,  63],
       [ 66,  87],
       [ 78,  88],
       [ 63,  60]], dtype=int32)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [215]:
arr = np.arange(10)
arr[(arr>3) & (arr<8)] *= -1
arr

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [216]:
#print(sum(range(5),-1))
#from numpy import *
#print(sum(range(5),-1))
print(sum(range(5),-1))
print(np.sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [217]:
Z = np.arange(5)

# Test each expression
print(Z**Z)        # Legal
print(2 << Z >> 2) # Legal  
print(Z <- Z)      # Legal (Z < -Z)
print(1j*Z)        # Legal
print(Z/1/1)       # Legal
# print(Z<Z>Z)     # Illegal - ValueError

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [218]:
# Result 1: nan
print(np.array(0) / np.array(0))

# Result 2: 0
print(np.array(0) // np.array(0))

# Result 3: Very large negative number
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\3331637747.py:2: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\3331637747.py:5: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\3331637747.py:8: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [219]:
Z = np.random.uniform(-10, 10, 10)
print("Original:", Z)
print("Rounded away from zero:", np.copysign(np.ceil(np.abs(Z)), Z))

Original: [ 9.14268379  2.87512861 -7.52410001  8.08974101 -1.62522152  5.07262985
 -3.26116884 -3.72722279  3.74295846  1.68726593]
Rounded away from zero: [10.  3. -8.  9. -2.  6. -4. -4.  4.  2.]


#### 30. How to find common values between two arrays? (★☆☆)

In [220]:
Z1 = np.random.randint(0, 10, 10)
Z2 = np.random.randint(0, 10, 10)
print("Z1:", Z1)
print("Z2:", Z2)
print("Common values:", np.intersect1d(Z1, Z2))

Z1: [6 5 6 2 7 1 3 4 8 4]
Z2: [6 3 5 6 7 5 2 0 4 5]
Common values: [2 3 4 5 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [221]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print("Result:", Z)
_ = np.seterr(**defaults)

Result: [inf]


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [222]:
print("np.sqrt(-1):", np.sqrt(-1))
print("np.emath.sqrt(-1):", np.emath.sqrt(-1))
print("Are they equal?", np.sqrt(-1) == np.emath.sqrt(-1))

np.sqrt(-1): nan
np.emath.sqrt(-1): 1j
Are they equal? False


C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\461198841.py:1: RuntimeWarning: invalid value encountered in sqrt
  print("np.sqrt(-1):", np.sqrt(-1))
C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\461198841.py:3: RuntimeWarning: invalid value encountered in sqrt
  print("Are they equal?", np.sqrt(-1) == np.emath.sqrt(-1))


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [223]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2025-10-27
Today: 2025-10-28
Tomorrow: 2025-10-29


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [224]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print("July 2016 dates:")
print(Z)

July 2016 dates:
['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [225]:
A = np.ones(3) * 1
B = np.ones(3) * 2
print("A:", A)
print("B:", B)
np.add(A, B, out=B)
print("B after A+B:", B)
np.divide(A, 2, out=A)
print("A after A/2:", A)
np.negative(A, out=A)
print("A after -A:", A)
np.multiply(A, B, out=A)
print("Final result:", A)

A: [1. 1. 1.]
B: [2. 2. 2.]
B after A+B: [3. 3. 3.]
A after A/2: [0.5 0.5 0.5]
A after -A: [-0.5 -0.5 -0.5]
Final result: [-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [226]:
Z = np.random.uniform(0, 10, 10)
print("Original:", Z)
print("Method 1 (Z - Z%1):", Z - Z%1)
print("Method 2 (floor):", np.floor(Z))
print("Method 3 (ceil-1):", np.ceil(Z)-1)
print("Method 4 (astype):", Z.astype(int))

Original: [3.03244086 1.107693   4.77927687 1.30530307 6.79136444 5.83828254
 2.91622706 0.6419033  4.85500308 6.42604719]
Method 1 (Z - Z%1): [3. 1. 4. 1. 6. 5. 2. 0. 4. 6.]
Method 2 (floor): [3. 1. 4. 1. 6. 5. 2. 0. 4. 6.]
Method 3 (ceil-1): [3. 1. 4. 1. 6. 5. 2. 0. 4. 6.]
Method 4 (astype): [3 1 4 1 6 5 2 0 4 6]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [227]:
Z = np.zeros((5, 5))
Z += np.arange(5)
print("Matrix with row values 0-4:")
print(Z)

Matrix with row values 0-4:
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [228]:
def generate():
    for x in range(10):
        yield x

Z = np.fromiter(generate(), dtype=float, count=-1)
print("Array from generator:", Z)

Array from generator: [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [229]:
Z = np.linspace(0, 1, 12)[1:-1]
print("Vector (0 to 1 excluded):", Z)

Vector (0 to 1 excluded): [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [230]:
Z = np.random.random(10)
print("Before sort:", Z)
Z.sort()
print("After sort:", Z)

Before sort: [0.81314271 0.02592778 0.87147617 0.38181591 0.6321656  0.05171749
 0.15729954 0.30990624 0.09680805 0.71742814]
After sort: [0.02592778 0.05171749 0.09680805 0.15729954 0.30990624 0.38181591
 0.6321656  0.71742814 0.81314271 0.87147617]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [231]:
Z = np.arange(10)
print("Array:", Z)
print("Sum using add.reduce:", np.add.reduce(Z))

Array: [0 1 2 3 4 5 6 7 8 9]
Sum using add.reduce: 45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [232]:
A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)
print("A:", A)
print("B:", B)
print("Are they equal?", np.allclose(A, B))

A: [0 1 1 0 0]
B: [1 0 0 0 0]
Are they equal? False


#### 43. Make an array immutable (read-only) (★★☆)

In [233]:
Z = np.zeros(10)
Z.flags.writeable = False
print("Array is now read-only")
print("Z:", Z)

Array is now read-only
Z: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [234]:
Z = np.random.random((10, 2))
print("Cartesian coordinates:")
print(Z)
X, Y = Z[:, 0], Z[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)
print("Polar R (radius):", R)
print("Polar T (angle):", T)

Cartesian coordinates:
[[0.32299202 0.99696063]
 [0.58405797 0.6274097 ]
 [0.67712502 0.58357462]
 [0.10209097 0.20825361]
 [0.90968128 0.96368284]
 [0.71869314 0.93025251]
 [0.66502442 0.097762  ]
 [0.81221442 0.73036275]
 [0.9609105  0.58545469]
 [0.57099904 0.77739434]]
Polar R (radius): [1.04797631 0.8571853  0.89390023 0.23193131 1.32521872 1.17553799
 0.67217177 1.09230124 1.12521384 0.96456304]
Polar T (angle): [1.25749024 0.82116737 0.71132877 1.11499987 0.81421616 0.91300084
 0.1459597  0.73238624 0.54720838 0.93728682]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [235]:
Z = np.random.random(10)
print("Original:", Z)
print("Max index:", Z.argmax())
Z[Z.argmax()] = 0
print("After replacing max:", Z)

Original: [0.06644356 0.05248633 0.76406391 0.75217609 0.78216357 0.75165518
 0.57272453 0.79227946 0.96937    0.42007742]
Max index: 8
After replacing max: [0.06644356 0.05248633 0.76406391 0.75217609 0.78216357 0.75165518
 0.57272453 0.79227946 0.         0.42007742]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [236]:
Z = np.zeros((5, 5), [('x', float), ('y', float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print("Structured array with x,y coordinates:")
print(Z)

Structured array with x,y coordinates:
[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [237]:
X = np.arange(8)
Y = X + 0.5
print("X:", X)
print("Y:", Y)
C = 1.0 / np.subtract.outer(X, Y)
print("Cauchy matrix:")
print(C)

X: [0 1 2 3 4 5 6 7]
Y: [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
Cauchy matrix:
[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [238]:
for dtype in [np.int8, np.int32, np.int64]:
    print(f"{dtype.__name__}: min={np.iinfo(dtype).min}, max={np.iinfo(dtype).max}")
for dtype in [np.float32, np.float64]:
    print(f"{dtype.__name__}: min={np.finfo(dtype).min}, max={np.finfo(dtype).max}")

int8: min=-128, max=127
int32: min=-2147483648, max=2147483647
int64: min=-9223372036854775808, max=9223372036854775807
float32: min=-3.4028234663852886e+38, max=3.4028234663852886e+38
float64: min=-1.7976931348623157e+308, max=1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [239]:
np.set_printoptions(threshold=np.inf)
Z = np.zeros((40, 40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [240]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
print("Array:", Z)
print("Target value:", v)
index = (np.abs(Z - v)).argmin()
print("Closest value:", Z[index])

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
Target value: 10.308308697313851
Closest value: 10


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [241]:
Z = np.zeros(10, [('position', [('x', float), ('y', float)]), ('color', [('r', float), ('g', float), ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [242]:
Z = np.random.random((10, 2))
X, Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
print(D)

[[0.         0.09222849 0.36907689 0.60252575 0.32607212 0.2999135
  0.84325962 0.78517793 0.65551714 0.06931742]
 [0.09222849 0.         0.36626926 0.65328591 0.30113258 0.38013331
  0.89926539 0.8125019  0.70475879 0.05477093]
 [0.36907689 0.36626926 0.         0.39029069 0.09884037 0.36546954
  0.63134214 0.46810912 0.42879751 0.32361478]
 [0.60252575 0.65328591 0.39029069 0.         0.48527836 0.3600768
  0.24906884 0.26252927 0.05386615 0.59871689]
 [0.32607212 0.30113258 0.09884037 0.48527836 0.         0.40293083
  0.7286932  0.56371413 0.5256784  0.26834664]
 [0.2999135  0.38013331 0.36546954 0.3600768  0.40293083 0.
  0.57454451 0.598406   0.41307202 0.33020563]
 [0.84325962 0.89926539 0.63134214 0.24906884 0.7286932  0.57454451
  0.         0.30077346 0.20332741 0.84452283]
 [0.78517793 0.8125019  0.46810912 0.26252927 0.56371413 0.598406
  0.30077346 0.         0.22652995 0.76168902]
 [0.65551714 0.70475879 0.42879751 0.05386615 0.5256784  0.41307202
  0.20332741 0.22652995 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [243]:
Z = np.arange(10, dtype=np.float32)
print("Original:", Z.dtype)
Z = Z.view(np.int32)
print("New dtype:", Z.dtype)

Original: float32
New dtype: int32


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [244]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int32)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [245]:
Z = np.arange(9).reshape(3, 3)
for index, value in np.ndenumerate(Z):
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [246]:
X, Y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))
D = np.sqrt(X*X + Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu)**2 / (2.0 * sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [247]:
n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False), 1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [248]:
X = np.random.rand(5, 10)
print("Original matrix:")
print(X)
Y = X - X.mean(axis=1, keepdims=True)
print("After subtracting row means:")
print(Y)

Original matrix:
[[0.38711431 0.58765671 0.47587906 0.93285293 0.10118308 0.60603526
  0.65676662 0.54880493 0.26645576 0.95245883]
 [0.23738803 0.64404777 0.29074411 0.38346076 0.25888296 0.10757755
  0.97739169 0.01490846 0.85249037 0.64706748]
 [0.41743896 0.94696721 0.68512585 0.39017114 0.64615156 0.5567497
  0.43275217 0.12369545 0.42883599 0.67475719]
 [0.27682247 0.73408637 0.81283833 0.30747406 0.85546091 0.78982297
  0.79000187 0.11768763 0.56382662 0.02855997]
 [0.02741501 0.81570299 0.09248071 0.19235774 0.16863049 0.28923046
  0.85816848 0.71200666 0.55221119 0.07090299]]
After subtracting row means:
[[-0.16440643  0.03613596 -0.07564169  0.38133218 -0.45033767  0.05451451
   0.10524587 -0.00271582 -0.28506499  0.40093808]
 [-0.20400789  0.20265185 -0.1506518  -0.05793515 -0.18251296 -0.33381837
   0.53599577 -0.42648746  0.41109445  0.20567156]
 [-0.11282556  0.41670269  0.15486133 -0.14009339  0.11588704  0.02648517
  -0.09751235 -0.40656907 -0.10142853  0.14449267]
 [-0

#### 59. How to sort an array by the nth column? (★★☆)

In [249]:
Z = np.random.randint(0, 10, (3, 3))
print("Original array:")
print(Z)
print("Sorted by 2nd column:")
print(Z[Z[:,1].argsort()])

Original array:
[[0 3 8]
 [8 8 2]
 [0 1 0]]
Sorted by 2nd column:
[[0 1 0]
 [0 3 8]
 [8 8 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [250]:
Z = np.random.randint(0, 3, (3, 10))
print("Array:")
print(Z)
print("Has null columns:", (~Z.any(axis=0)).any())

Array:
[[1 1 0 2 0 0 1 2 0 0]
 [0 1 1 0 2 2 1 1 0 0]
 [0 2 1 1 0 1 0 0 1 2]]
Has null columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [251]:
Z = np.arange(100)
v = np.random.uniform(0, 100)
index = (np.abs(Z - v)).argmin()
print("Target:", v)
print("Nearest:", Z[index])

Target: 8.206749628108877
Nearest: 8


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [252]:
A = np.arange(3).reshape(1, 3)
B = np.arange(3).reshape(3, 1)
it = np.nditer([A, B, None])
for x, y, z in it:
    z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [253]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "my_array")
print(Z.name)

my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [254]:
Z = np.ones(10)
I = np.random.randint(0, len(Z), 20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 3. 2. 3. 3. 2. 3. 1. 4. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [255]:
X = [1, 2, 3, 4, 5, 6]
I = [1, 3, 9, 3, 4, 1]
F = np.bincount(I, X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [256]:
w, h = 16, 16
I = np.random.randint(0, 256, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
print("Number of unique colors:", len(colors))

Number of unique colors: 256


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [257]:
A = np.random.randint(0, 10, (3, 4, 3, 4))
print("Original shape:", A.shape)
sum_result = A.sum(axis=(-2, -1))
print("After sum over last 2 axes:", sum_result.shape)
print(sum_result)

Original shape: (3, 4, 3, 4)
After sum over last 2 axes: (3, 4)
[[54 48 56 55]
 [62 61 57 57]
 [62 55 56 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [258]:
D = np.random.uniform(0, 1, 100)
S = np.random.randint(0, 10, 100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.46901334 0.55393342 0.35048836 0.47222329 0.44358577 0.48171966
 0.51838734 0.51965336 0.58671191 0.3468109 ]


#### 69. How to get the diagonal of a dot product? (★★★)

In [259]:
A = np.random.uniform(0, 1, (5, 5))
B = np.random.uniform(0, 1, (5, 5))
print("Using diag:", np.diag(np.dot(A, B)))
print("Using einsum:", np.einsum("ij,ji->i", A, B))

Using diag: [0.52534023 1.62184933 1.24260419 0.78364775 1.623022  ]
Using einsum: [0.52534023 1.62184933 1.24260419 0.78364775 1.623022  ]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [260]:
Z = np.array([1, 2, 3, 4, 5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z) - 1) * nz)
Z0[::nz + 1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [261]:
A = np.ones((5, 5, 3))
B = 2 * np.ones((5, 5))
print(A * B[:, :, None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [262]:
A = np.arange(25).reshape(5, 5)
print("Original:")
print(A)
A[[0, 1]] = A[[1, 0]]
print("After swapping rows 0 and 1:")
print(A)

Original:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
After swapping rows 0 and 1:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [263]:
faces = np.random.randint(0, 100, (10, 3))
F = np.roll(faces.repeat(2, axis=1), -1, axis=1)
F = F.reshape(len(F) * 3, 2)
F = np.sort(F, axis=1)
G = F.view(dtype=[('p0', F.dtype), ('p1', F.dtype)])
G = np.unique(G)
print(G)

[( 0, 41) ( 0, 76) ( 0, 79) ( 0, 94) ( 8, 68) ( 8, 95) ( 9, 63) ( 9, 76)
 (14, 63) (14, 89) (24, 24) (24, 58) (33, 36) (33, 42) (36, 42) (37, 69)
 (37, 79) (40, 71) (40, 92) (41, 94) (44, 68) (44, 75) (63, 76) (63, 89)
 (68, 75) (68, 95) (69, 79) (71, 92) (76, 79)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [264]:
C = np.bincount([1, 1, 2, 3, 4, 4, 6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [265]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [266]:
from numpy.lib import stride_tricks
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [267]:
Z = np.random.randint(0, 2, 100, dtype=bool)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1, 1, 100)
np.negative(Z, out=Z)

array([-0.24384455,  0.16461449, -0.42904108, -0.08543433, -0.59448056,
        0.02558384, -0.11430364, -0.03287999,  0.75808477, -0.19347914,
       -0.91603449,  0.70776186, -0.47678472, -0.86232431,  0.86473241,
        0.00208477, -0.31486214,  0.72495445, -0.60242146,  0.93304874,
       -0.15094182, -0.14805423, -0.23043457, -0.49828677,  0.11376759,
       -0.7050793 ,  0.78669083,  0.80722254,  0.34554096, -0.06925099,
       -0.74733553,  0.71159978,  0.47587416, -0.49118785, -0.74195707,
        0.23833839,  0.40067225,  0.39955448,  0.14841465,  0.31253243,
       -0.60666917, -0.71390166, -0.0638564 , -0.16888842, -0.0297081 ,
       -0.72818596,  0.82849607, -0.46017373,  0.41959365, -0.2043672 ,
        0.12908993, -0.97697478,  0.28861482,  0.05504324,  0.07330727,
       -0.88237602,  0.75307953, -0.53450672, -0.96654846,  0.21737238,
       -0.46435221,  0.92575954,  0.88073667, -0.99811778, -0.64486501,
       -0.5301675 , -0.12151063, -0.08123399, -0.69709362,  0.09

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [268]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T
    return np.sqrt(((D - p)**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (1, 2))
print(distance(P0, P1, p))

[ 3.44454797 11.04294188 10.80978536 15.13727198  0.6535998  16.04053037
 11.84663472  6.40760076  8.01948805 10.69163801]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [269]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U), 1)
    D = P0 + U * T
    return np.sqrt(((D - p)**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10, 2))
P1 = np.random.uniform(-10, 10, (10, 2))
p = np.random.uniform(-10, 10, (10, 2))
print(distance(P0, P1, p))

[ 2.52596157  5.83191123  2.90465421  3.28381412  2.40296764  6.63944837
  7.41523317  5.05063592 16.15742584 10.15388525]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [270]:
Z = np.random.randint(0, 10, (10, 10))
shape = (5, 5)
fill = 0
position = (5, 5)

R = np.ones(shape, dtype=Z.dtype) * fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P - Rs // 2)
Z_stop = (Z_start + Rs)

R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop - Zs, 0))).tolist()
Z_stop = (np.minimum(Z_stop, Zs)).tolist()

r = tuple([slice(start, stop) for start, stop in zip(R_start, R_stop)])
z = tuple([slice(start, stop) for start, stop in zip(Z_start, Z_stop)])
R[r] = Z[z]
print(R)

[[2 9 6 9 2]
 [4 3 4 2 0]
 [6 7 6 4 1]
 [4 7 7 1 1]
 [9 1 2 3 6]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [271]:
Z = np.arange(1, 15, dtype=np.uint32)
R = stride_tricks.as_strided(Z, (11, 4), (4, 4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [272]:
Z = np.random.uniform(0, 1, (10, 10))
U, S, V = np.linalg.svd(Z)
rank = np.sum(S > 1e-10)
print("Matrix rank:", rank)

Matrix rank: 10


#### 83. How to find the most frequent value in an array?

In [273]:
Z = np.random.randint(0, 10, 50)
print("Array:", Z)
print("Most frequent value:", np.bincount(Z).argmax())

Array: [5 5 0 2 6 8 4 2 7 6 3 3 9 4 9 9 4 2 5 2 6 2 0 7 8 9 4 4 2 8 9 6 6 4 6 7 6
 0 9 0 0 7 8 3 0 3 6 7 9 9]
Most frequent value: 6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [274]:
Z = np.random.randint(0, 5, (10, 10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 2 0]
   [4 3 3]
   [4 1 2]]

  [[2 0 0]
   [3 3 4]
   [1 2 0]]

  [[0 0 4]
   [3 4 4]
   [2 0 1]]

  [[0 4 2]
   [4 4 3]
   [0 1 1]]

  [[4 2 2]
   [4 3 1]
   [1 1 0]]

  [[2 2 3]
   [3 1 3]
   [1 0 0]]

  [[2 3 3]
   [1 3 4]
   [0 0 2]]

  [[3 3 4]
   [3 4 3]
   [0 2 3]]]


 [[[4 3 3]
   [4 1 2]
   [3 2 4]]

  [[3 3 4]
   [1 2 0]
   [2 4 1]]

  [[3 4 4]
   [2 0 1]
   [4 1 2]]

  [[4 4 3]
   [0 1 1]
   [1 2 2]]

  [[4 3 1]
   [1 1 0]
   [2 2 3]]

  [[3 1 3]
   [1 0 0]
   [2 3 1]]

  [[1 3 4]
   [0 0 2]
   [3 1 1]]

  [[3 4 3]
   [0 2 3]
   [1 1 0]]]


 [[[4 1 2]
   [3 2 4]
   [3 4 4]]

  [[1 2 0]
   [2 4 1]
   [4 4 1]]

  [[2 0 1]
   [4 1 2]
   [4 1 0]]

  [[0 1 1]
   [1 2 2]
   [1 0 1]]

  [[1 1 0]
   [2 2 3]
   [0 1 4]]

  [[1 0 0]
   [2 3 1]
   [1 4 2]]

  [[0 0 2]
   [3 1 1]
   [4 2 1]]

  [[0 2 3]
   [1 1 0]
   [2 1 2]]]


 [[[3 2 4]
   [3 4 4]
   [1 3 0]]

  [[2 4 1]
   [4 4 1]
   [3 0 3]]

  [[4 1 2]
   [4 1 0]
   [0 3 0]]

  [[1 2 2]
   [1 0 1]
   [3 0 3]]

  [[2 2 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [275]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i, j = index
        super(Symetric, self).__setitem__((i, j), value)
        super(Symetric, self).__setitem__((j, i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0, 10, (5, 5)))
S[2, 3] = 42
print(S)

[[ 2 10  7 10  7]
 [10  7 12 10 11]
 [ 7 12  9 42  9]
 [10 10 42  4 13]
 [ 7 11  9 13  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [276]:
p, n = 10, 20
M = np.ones((p, n, n))
V = np.ones((p, n, 1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [277]:
Z = np.arange(16).reshape(4, 4)
k = 2
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[10 18]
 [42 50]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [278]:
def iterate(Z):
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2]                 + Z[1:-1, 2:] +
         Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])
    birth = (N == 3) & (Z[1:-1, 1:-1] == 0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0, 2, (10, 10))
print("Initial state:")
print(Z)
for i in range(5):
    Z = iterate(Z)
print("\nAfter 5 iterations:")
print(Z)

Initial state:
[[0 0 1 1 1 1 0 0 1 0]
 [0 1 1 1 0 1 0 1 0 0]
 [1 1 0 1 0 0 0 1 1 0]
 [1 0 0 0 1 0 0 0 1 0]
 [0 1 1 0 1 0 1 1 1 1]
 [0 1 1 0 1 1 0 1 1 1]
 [1 0 0 0 0 1 1 1 0 1]
 [1 1 1 0 1 0 0 0 1 1]
 [0 0 1 0 1 0 0 0 0 0]
 [0 0 1 1 1 0 1 1 1 0]]

After 5 iterations:
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 0 0 0 0]
 [0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [279]:
Z = np.arange(100)
np.random.shuffle(Z)
n = 5
print("Array (first 20 elements):", Z[:20])
largest = Z[np.argpartition(-Z, n)[:n]]
print(f"\n{n} largest values:", largest)

Array (first 20 elements): [62 60 28 97 88 46 58 48 39 47 89 71 36 50 17 78 67 42 57 51]

5 largest values: [99 98 97 96 95]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [280]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = tuple(len(x) for x in arrays)
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    return ix

result = cartesian(([1, 2, 3], [4, 5], [6, 7]))
print("Cartesian product:")
print(result)

Cartesian product:
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [281]:
Z = np.array([("Hello", 2.5, 3), ("World", 3.6, 2)])
print("Regular array:")
print(Z)
R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats='S8, f8, i8')
print("\nRecord array:")
print(R)

Regular array:
[['Hello' '2.5' '3']
 ['World' '3.6' '2']]

Record array:
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


C:\Users\Bakir\AppData\Local\Temp\ipykernel_21752\3376599292.py:4: DeprecationWarning: numpy.core is deprecated and has been renamed to numpy._core. The numpy._core namespace contains private NumPy internals and its use is discouraged, as NumPy internals can change without warning in any release. In practice, most real-world usage of numpy.core is to access functionality in the public NumPy API. If that is the case, use the public NumPy API. If not, you are using NumPy internals. If you would still like to access an internal attribute, use numpy._core.records.
  R = np.core.records.fromarrays(Z.T, names='col1, col2, col3', formats='S8, f8, i8')


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [282]:
x = np.random.rand(int(1e6))

import time

start = time.time()
_ = x**3
t1 = time.time() - start
print(f"Method 1 (x**3): {t1:.6f} seconds")

start = time.time()
_ = x*x*x
t2 = time.time() - start
print(f"Method 2 (x*x*x): {t2:.6f} seconds")

start = time.time()
_ = np.power(x, 3)
t3 = time.time() - start
print(f"Method 3 (np.power): {t3:.6f} seconds")

Method 1 (x**3): 0.059000 seconds
Method 2 (x*x*x): 0.008001 seconds
Method 3 (np.power): 0.059000 seconds


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [283]:
A = np.random.randint(0, 5, (8, 3))
B = np.random.randint(0, 5, (2, 2))
print("Array A:")
print(A)
print("\nArray B:")
print(B)
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3, 1)).all(1))[0]
print("\nRows of A containing all elements of each row of B:")
print(rows)

Array A:
[[1 3 2]
 [4 3 2]
 [3 3 1]
 [4 3 3]
 [3 4 0]
 [1 0 2]
 [2 2 4]
 [4 4 2]]

Array B:
[[4 1]
 [3 4]]

Rows of A containing all elements of each row of B:
[0 1 2 3 4 6 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [284]:
Z = np.random.randint(0, 5, (10, 3))
print("Original matrix:")
print(Z)
E = np.all(Z[:, 1:] == Z[:, :-1], axis=1)
U = Z[~E]
print("\nRows with unequal values:")
print(U)

Original matrix:
[[3 1 1]
 [1 0 1]
 [4 4 0]
 [4 3 0]
 [1 3 0]
 [1 1 3]
 [2 0 2]
 [3 0 1]
 [3 4 2]
 [0 0 4]]

Rows with unequal values:
[[3 1 1]
 [1 0 1]
 [4 4 0]
 [4 3 0]
 [1 3 0]
 [1 1 3]
 [2 0 2]
 [3 0 1]
 [3 4 2]
 [0 0 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [285]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
print("Integers:", I)
B = ((I.reshape(-1, 1) & (2**np.arange(8))) != 0).astype(int)
print("\nBinary representation:")
print(B[:, ::-1])

Integers: [  0   1   2   3  15  16  32  64 128]

Binary representation:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [286]:
Z = np.random.randint(0, 2, (6, 3))
print("Original array:")
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print("\nUnique rows:")
print(uZ)

Original array:
[[0 0 0]
 [1 1 0]
 [1 0 1]
 [1 0 0]
 [0 0 0]
 [0 1 0]]

Unique rows:
[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [287]:
A = np.random.uniform(0, 1, 10)
B = np.random.uniform(0, 1, 10)
print("A:", A)
print("B:", B)

print("\nInner product:", np.einsum('i,i', A, B))
print("np.inner equivalent:", np.inner(A, B))

print("\nOuter product shape:", np.einsum('i,j', A, B).shape)
print("np.outer equivalent shape:", np.outer(A, B).shape)

print("\nSum:", np.einsum('i->', A))
print("np.sum equivalent:", np.sum(A))

print("\nElement-wise mul:", np.einsum('i,i->i', A, B))
print("A*B equivalent:", (A*B))

A: [0.77634548 0.48884305 0.59351896 0.88223088 0.60037838 0.57715385
 0.12726217 0.43349224 0.01260142 0.49252381]
B: [0.73062856 0.59988239 0.45550541 0.20033118 0.93541203 0.71711422
 0.75659612 0.75014852 0.00737364 0.78743545]

Inner product: 3.0924376271714697
np.inner equivalent: 3.0924376271714706

Outer product shape: (10, 10)
np.outer equivalent shape: (10, 10)

Sum: 4.984350255600079
np.sum equivalent: 4.984350255600079

Element-wise mul: [5.67220183e-01 2.93248335e-01 2.70351098e-01 1.76738357e-01
 5.61601164e-01 4.13885238e-01 9.62860628e-02 3.25183562e-01
 9.29183531e-05 3.87830709e-01]
A*B equivalent: [5.67220183e-01 2.93248335e-01 2.70351098e-01 1.76738357e-01
 5.61601164e-01 4.13885238e-01 9.62860628e-02 3.25183562e-01
 9.29183531e-05 3.87830709e-01]


#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [288]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
print("Original points:", len(x))

dr = (np.diff(x)**2 + np.diff(y)**2)**.5
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
print("Cumulative distances calculated")

r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)
y_int = np.interp(r_int, r, y)
print("Equidistant sampled points:", len(x_int))

Original points: 315
Cumulative distances calculated
Equidistant sampled points: 200


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [289]:
n = 24
X = np.random.randint(0, n+1, (10, 3))
print("Array X:")
print(X)
print("\nRow sums:", X.sum(axis=1))
valid = (X.sum(axis=1) == n) & np.all((X >= 0), axis=1)
result = X[valid]
print(f"\nRows that sum to {n}:")
print(result)

Array X:
[[ 6 18 10]
 [17 19 19]
 [12  5 14]
 [15 24 18]
 [13  3  8]
 [ 3 19 17]
 [ 5  0 18]
 [22 14 23]
 [ 1 22 20]
 [20  1  7]]

Row sums: [34 55 31 57 24 39 23 59 43 28]

Rows that sum to 24:
[[13  3  8]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [290]:
X = np.random.randn(100)
print("Original array mean:", X.mean())
print("Original array std:", X.std())

N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
print(f"\nBootstrap samples: {N}")
print("Bootstrap means (first 10):", means[:10])

confint = np.percentile(means, [2.5, 97.5])
print("\n95% confidence interval for the mean:")
print(f"Lower bound: {confint[0]:.4f}")
print(f"Upper bound: {confint[1]:.4f}")

Original array mean: 0.09954778532131883
Original array std: 1.0556765007961209

Bootstrap samples: 1000
Bootstrap means (first 10): [0.04349729 0.08289594 0.23368903 0.0758498  0.09078206 0.11437169
 0.09670288 0.00379665 0.03510894 0.08229658]

95% confidence interval for the mean:
Lower bound: -0.1034
Upper bound: 0.2949
